[package]
name = "xy_os"
version = "0.1.0"
authors = ["z"]
edition = "2018"

[profile.dev]
panic = "abort"
opt-level = 3

[profile.release]
panic = "abort"

[dependencies]
bbl = {path = "crate/bbl"}
xmas-elf = "0.6.2"
fixedvec = "0.2.3"
